environment:
  matrix:
    - CMAKE_GENERATOR: "MinGW Makefiles"
      MINGW_PATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - CMAKE_GENERATOR: "MinGW Makefiles"
      MINGW_PATH: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - CMAKE_GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
build_script:
  # See https://github.com/jibsen/brieflz/blob/master/appveyor.yml
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: set PATH=%MINGW_PATH%;%PATH%
  - cmd: cmake -G "%CMAKE_GENERATOR%" .
  - cmd: cmake --build . --config Release
  - cmd: ctest --output-on-failure -a -j8 -C Release
